diff --git a/Dockerfile b/Dockerfile
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,23 +1,23 @@
-FROM ruby:2.6-slim
+FROM ruby:3.0-slim

 WORKDIR /srv/slate

 EXPOSE 4567

-COPY Gemfile .
-COPY Gemfile.lock .
-
 RUN apt-get update \
     && apt-get install -y --no-install-recommends \
         build-essential \
         git \
         nodejs \
-    && gem install bundler \
-    && bundle install \
-    && apt-get remove -y build-essential git \
+        openssh-client \
     && apt-get autoremove -y \
     && rm -rf /var/lib/apt/lists/*

+COPY Gemfile .
+COPY Gemfile.lock .
+
+RUN bundle install
+
 COPY . /srv/slate

 RUN chmod +x /srv/slate/slate.sh
