services:

  slate:
    build:
      context: ./
    volumes:
      - ./:/srv/slate/
    ports:
      - 80:4567
    entrypoint: >-
      /usr/bin/env bash -e -c
    command:
      - >-
        bundle install &&
        /srv/slate/slate.sh build &&
        /srv/slate/slate.sh serve;
