---
version: '3'
services:
  slate:
    build:
      context: .
    volumes:
      - .:/srv/slate
    ports:
      - 4567:4567
    command: sh -c '
      bundle install &&
      if [ "$BYEBUG" -eq "1" ];
        then echo "sleeping";
        sleep 100d;
      else
        bundle exec middleman server;
      fi
      '
